name: PR Sanity Check

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js 16.x
        uses: actions/setup-node@v1
        with:
        node-version: 16.x

      - name: Install Packages
        run: |
          npm install
      - name: Lint check
        run: |
          npm run lint
      - name: Test check
        run: |
          npm run test
